Set up for async actions
arinaldi/air-tony pull request #2
Opened 2017-04-25 16:19 UTC by arinaldi

Add promises and verify data returns from static API call.

2017-04-25 17:16 UTC, ashleymichal requested changes

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +  console.log(location, json);
1. avoid committing console.log statements to your history.

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +    desc: json.breezometer_description
go with full word `description` for your variable. we're not hurting for space, readability will be your friend in the future.

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +    //have parameter to fetch be Promise from my api module
remove unnecessary comments.

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +    return fetch(`https://api.breezometer.com/baqi/?lat=40.7324296&lon=-73.9977264&key=fbbb89795db54612ad9598e2ce77b709&fields=breezometer_aqi,breezometer_color,breezometer_description,datetime`)
extract URLs and endpoint paths to constants

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +        //const json = response.json();
again.

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +        //return response
and here.. etc. If these are todos, mark them `// TODO: lorem ipsum...`

2017-04-25 17:16 UTC, ashleymichal commented on src/actions/index.js
> +      .catch(err => {})//dispatch error state)
avoid inline comments.

2017-04-25 17:16 UTC, ashleymichal commented on src/components/HistoryTable.js
> +     return (
intentional whitespace change? Tangentially, have we set up a linter for you?

2017-04-25 17:16 UTC, ashleymichal commented on src/containers/App.js
>  //import PropTypes from 'prop-types';
unused?

2017-04-25 17:16 UTC, ashleymichal commented on src/containers/App.js
>  class App extends Component {
this could be a pure function :-D

2017-04-25 20:32 UTC, arinaldi commented on src/actions/index.js
> +  console.log(location, json);
Done.

2017-04-25 20:32 UTC, arinaldi commented on src/actions/index.js
> +    desc: json.breezometer_description
Done.

2017-04-25 20:33 UTC, arinaldi commented on src/actions/index.js
> +    //have parameter to fetch be Promise from my api module
Done.

2017-04-25 20:36 UTC, arinaldi commented on src/actions/index.js
> +    return fetch(`https://api.breezometer.com/baqi/?lat=40.7324296&lon=-73.9977264&key=fbbb89795db54612ad9598e2ce77b709&fields=breezometer_aqi,breezometer_color,breezometer_description,datetime`)
Done.

2017-04-25 20:36 UTC, arinaldi commented on src/actions/index.js
> +        //const json = response.json();
Done.

2017-04-25 20:36 UTC, arinaldi commented on src/actions/index.js
> +        //return response
Done.

2017-04-25 20:37 UTC, arinaldi commented on src/actions/index.js
> +      .catch(err => {})//dispatch error state)
Done.

2017-04-25 20:37 UTC, arinaldi commented on src/components/HistoryTable.js
> +     return (
Done.

2017-04-25 20:38 UTC, arinaldi commented on src/containers/App.js
>  //import PropTypes from 'prop-types';
Done.

2017-04-25 20:56 UTC, arinaldi commented on src/containers/App.js
>  class App extends Component {
Done.

2017-04-25 20:56 UTC, ghaynes1292 commented on src/reducers/index.js
>  const rootReducer = combineReducers({ locations });
You don't need to combine with a single reducer

2017-04-25 21:12 UTC, arinaldi commented on src/reducers/index.js
>  const rootReducer = combineReducers({ locations });
Done.

2017-04-26 14:27 UTC, ghaynes1292 approved these changes

2017-04-26 14:28 UTC, merged