Save state of last 5 locations to localStorage
arinaldi/air-tony pull request #5
Opened 2017-04-26 19:54 UTC by arinaldi

2017-04-27 21:34 UTC, cjessett commented on src/actions/index.js
> +    date: newLocation.date,
destructure these keys from `newLocation` like `const { date, name, aqi, ...etc } = newLocation`

2017-04-27 21:34 UTC, cjessett commented on src/actions/index.js
> +    date: newLocation.date,
then use object assignment shorthand like `return { date, name, aqi, ...etc }`

2017-04-27 21:36 UTC, cjessett commented on src/actions/index.js
>  export const fetchLocation = location => {
you should be consistent with how you define functions, above you use `function` syntax whereas here you are assigning an anonymous function to a `const`

2017-04-27 22:10 UTC, jorions approved these changes
LGTM 5/5 would CR again

2017-04-27 22:13 UTC, cjessett commented on src/utilities/index.js
> +  const arrayOfObjects = JSON.parse(item);
no need to name this, just return the result of parsing

2017-04-27 22:15 UTC, cjessett requested changes

2017-04-27 22:15 UTC, cjessett commented on src/utilities/index.js
> +  const newDate = {
same here just return the thing, don't name it

2017-04-28 14:33 UTC, arinaldi commented on src/utilities/index.js
> +  const arrayOfObjects = JSON.parse(item);
Done.

2017-04-28 14:38 UTC, arinaldi commented on src/utilities/index.js
> +  const newDate = {
Done.

2017-04-28 14:46 UTC, ghaynes1292 requested changes

2017-04-28 14:46 UTC, ghaynes1292 commented on src/api/index.js
> +// TODO: catch for bad response
Lets remove these comments and just add it into the PR for error handling

2017-04-28 14:49 UTC, arinaldi commented on src/api/index.js
> +// TODO: catch for bad response
Done.

2017-04-28 14:50 UTC, arinaldi commented on src/actions/index.js
> +    date: newLocation.date,
Done.

2017-04-28 14:51 UTC, arinaldi commented on src/actions/index.js
>  export const fetchLocation = location => {
Done.

2017-04-28 14:54 UTC, ghaynes1292 approved these changes

2017-04-28 14:55 UTC, merged